# Generated by Django 4.0.3 on 2022-06-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='rule')),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Team Name')),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enfuego.teams')),
                ('gamesplayed', models.PositiveIntegerField(verbose_name='games played')),
                ('gameswon', models.PositiveIntegerField(verbose_name='games won')),
                ('gamesdraw', models.PositiveIntegerField(verbose_name='games draw')),
                ('gameslost', models.PositiveIntegerField(verbose_name='games lost')),
                ('goalsscored', models.PositiveIntegerField(verbose_name='goals scored')),
                ('goalsconceded', models.PositiveIntegerField(verbose_name='goals conceded')),
                ('goaldifference', models.IntegerField(verbose_name='goal difference')),
                ('points', models.PositiveIntegerField(verbose_name='points')),
            ],
            options={
                'ordering': ['-points', '-goaldifference'],
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Player Name')),
                ('goalsscored', models.PositiveIntegerField(verbose_name='Goals Scored')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enfuego.teams')),
            ],
            options={
                'ordering': ['-goalsscored'],
            },
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchnumber', models.PositiveIntegerField(verbose_name='match number')),
                ('scorea', models.PositiveIntegerField(blank=True, null=True, verbose_name='teama score')),
                ('scoreb', models.PositiveIntegerField(blank=True, null=True, verbose_name='teamb score')),
                ('date', models.DateField(verbose_name='match date')),
                ('finished', models.BooleanField()),
                ('teama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teama', to='enfuego.teams')),
                ('teamb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamb', to='enfuego.teams')),
            ],
            options={
                'ordering': ['matchnumber'],
            },
        ),
    ]
